/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.examples.restjerseyconnector;

import org.junit.Assert;
import org.junit.Test;


public class RestJerseyConnectorTest {
    
	@Test
	public void dummyTest() {
		Assert.assertTrue(true);
	}
}
